# Generated by Django 3.1.3 on 2021-02-28 18:57

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sketchbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artimage', versatileimagefield.fields.VersatileImageField(blank=True, height_field='imgheight', null=True, upload_to='Sketchbook', verbose_name='Image', width_field='imgwidth')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('imgheight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height (Pixels)')),
                ('imgwidth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width (Pixels)')),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('media', models.CharField(choices=[('A', 'Acrylic'), ('W', 'Watercolor'), ('MM', 'Multimedia'), ('G', 'Gouache'), ('O', 'Oil'), ('P', 'Pencil'), ('C', 'Charcoal'), ('PS', 'Pastel'), ('CO', 'Conte Crayon')], max_length=3)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('showOnWebsite', models.BooleanField(default=True)),
                ('weightedOrder', models.IntegerField(default=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sketchbook.category')),
            ],
            options={
                'verbose_name': 'Sketchbook image',
                'verbose_name_plural': 'Sketchbook images',
                'ordering': ['weightedOrder', 'id', 'title'],
            },
        ),
    ]
