# Generated by Django 3.2.6 on 2021-08-30 19:53

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sketchbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchbook',
            name='artimage',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='imgheight', null=True, upload_to='sketchbook', verbose_name='Image', width_field='imgwidth'),
        ),
        migrations.AlterField(
            model_name='sketchbook',
            name='media',
            field=models.CharField(choices=[('A', 'Acrylic'), ('W', 'Watercolor'), ('MM', 'Multimedia'), ('G', 'Gouache'), ('O', 'Oil'), ('P', 'Pencil'), ('PI', 'Pen & Ink'), ('C', 'Charcoal'), ('PS', 'Pastel'), ('CO', 'Conte Crayon')], max_length=3),
        ),
    ]
