# Generated by Django 3.1.3 on 2021-02-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='bodycontent',
            field=models.TextField(blank=True, null=True, verbose_name='Body Content for Home Page'),
        ),
    ]
