# Generated by Django 3.1.3 on 2021-01-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='media',
            field=models.CharField(choices=[('A', 'Acrylic'), ('W', 'Watercolor'), ('MM', 'Multimedia'), ('G', 'Gouache'), ('O', 'Oil'), ('P', 'Pencil'), ('C', 'Charcoal'), ('PS', 'Pastel'), ('CO', 'Conte Crayon')], max_length=3),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
