# Generated by Django 3.2.6 on 2022-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20210118_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['weightedOrder'], 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='weightedOrder',
            field=models.IntegerField(default=0),
        ),
    ]
